# Generated by Django 2.0.5 on 2018-06-28 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, upload_to='mentor/%Y/%m/%d')),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=15)),
                ('github', models.URLField(null=True)),
                ('languages', models.ManyToManyField(related_name='mentor_language', to='account.Languages')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ManyToManyField(related_name='mentor_skill', to='account.TechSkill')),
            ],
        ),
    ]
