# Generated by Django 2.0.5 on 2018-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='mentor_skill', to='account.TechSkill'),
        ),
    ]
