# Generated by Django 2.0.5 on 2018-06-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', max_length=15),
        ),
    ]
