# Generated by Django 2.0.5 on 2018-06-22 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='languages',
            field=models.ManyToManyField(related_name='mentor_language', to='account.Languages'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentor',
            name='skill',
            field=models.ManyToManyField(related_name='mentor_skill', to='account.TechSkill'),
        ),
    ]
