# Generated by Django 2.0.5 on 2018-06-23 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
