# Generated by Django 2.0.6 on 2018-07-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
