# Generated by Django 2.0.5 on 2018-05-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
