# Generated by Django 2.0.5 on 2018-05-30 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20180530_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
