# Generated by Django 2.0.5 on 2018-05-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180530_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='user',
        ),
    ]
