# Generated by Django 2.0.5 on 2018-05-31 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180531_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Languages', to_field='name'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sklii', to='account.TechSkill'),
        ),
    ]
