# Generated by Django 2.0.5 on 2018-06-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180531_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techskill',
            old_name='skill',
            new_name='skill_name',
        ),
    ]
