# Generated by Django 2.0.5 on 2018-06-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180602_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techskill',
            name='languages',
        ),
        migrations.AddField(
            model_name='techskill',
            name='languages',
            field=models.ManyToManyField(null=True, to='account.Languages'),
        ),
    ]
