# Generated by Django 2.0.5 on 2018-06-07 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_auto_20180602_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, upload_to='mentor/%Y/%m/%d')),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('languages', models.ManyToManyField(related_name='mentor_language', to='account.Languages')),
                ('profile', models.OneToOneField(default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='techskill',
            name='languages',
            field=models.ManyToManyField(to='account.Languages'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='skill',
            field=models.ManyToManyField(related_name='mentor_skill', to='account.TechSkill'),
        ),
    ]
