# Generated by Django 2.0.6 on 2018-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answertext', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('answer', models.BooleanField(default=True)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date publish')),
                ('closed', models.BooleanField(default=False)),
                ('upvote', models.IntegerField(blank=True, default=0)),
                ('downvote', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
    ]
